### ISSUE TITLE
pip install raises IOError

### ISSUE THREAD

**Issue by s-celles** [morse-talk/morse-talk#20]
Hello,

I'm using Mac OS X with Anaconda Python

```
$ pip install morse-talk --upgrade
Collecting morse-talk
  Using cached morse-talk-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-build-j3h8O8/morse-talk/setup.py", line 6, in <module>
        with open(path.join(here, 'DESCRIPTION.md')) as f:
    IOError: [Errno 2] No such file or directory: '/private/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-build-j3h8O8/morse-talk/DESCRIPTION.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-build-j3h8O8/morse-talk
(py2)pc:~ scls$ pip install morse-talk
Collecting morse-talk
  Using cached morse-talk-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-build-pzWcXf/morse-talk/setup.py", line 6, in <module>
        with open(path.join(here, 'DESCRIPTION.md')) as f:
    IOError: [Errno 2] No such file or directory: '/private/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-build-pzWcXf/morse-talk/DESCRIPTION.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-build-pzWcXf/morse-talk
```

**Comment by OrkoHunter** [comment]
Hello @scls19fr, thanks for reporting the issue. There was some problem with locating the description file and I really don't know why don't we document the setup files.

Anyways, pip install should be fixed by now. pypi will take some time to soak 0.1.3
