### ISSUE TITLE
string index out of range

### ISSUE THREAD

**Issue by A4-Tacks** [morse-talk/morse-talk#53]
```python
>>> morse_talk.decode('.    .')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lrne/Project/Git/morse-talk/morse_talk/decoding.py", line 45, in decode
    elif code[i+4] and code[i-1] != ' ':  # Check for '   '
         ~~~~^^^^^
IndexError: string index out of range
```

I don't understand the meaning of the two results of code 'code [i+4]': raise or return True

**Comment by A4-Tacks** [comment]
:(
